### ISSUE TITLE
Concurrency issues in use of DatastoreDB

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/appengine#117]
Servers that used DatastoreDB are susceptible to concurrency issues, where different concurrent requests share the same DatastoreDB instance. Specifically, the issue is as follows:

appengine registers a single gcloud:DatastoreDB instance upon server startup
 ↳ gcloud:DatastoreDB maintains a reference to a gcloud:Datastore (implemented by appengine:GrpcDatastoreImpl)
 ↳ appengine:GrpcDatastoreImpl maintains a reference to grpc:ClientChannel
 ↳ grpc:ClientChannel maintains a reference to an grpc:Http2ClientConnection
 ↳ grpc:Http2ClientConnection maintains state

This can cause issues whereby the client connection would throw for request B because it would think that it was in a closing state due to a call from request A.

**Comment by jonasfj** [comment]
What are the scenarios that can cause this to happen?

Is it only when thh HTTP2 connection is broken.

**Comment by tvolkert** [comment]
I can't reproduce it now... And the log records of when this happened have expired, so I can't find where the code was failing anymore.

I'll keep this open for a  while while I watch for instances of it happening again.

**Comment by tvolkert** [comment]
Ok, here's the error I was seeing:

```
Uncaught error in request handler: gRPC Error (14, Error making call: Bad state: The http/2 connection is finishing and can therefore not be used to make new streams.)
#0      GrpcDatastoreImpl.lookup (package:appengine/src/grpc_api_impl/datastore_impl.dart:149:39)
<asynchronous suspension>
#1      _lookupHelper (package:gcloud/src/db/db.dart:429:8)
#2      DatastoreDB.lookup (package:gcloud/src/db/db.dart:339:12)
#3      DatastoreDB.lookupValue (package:gcloud/src/db/db.dart:352:34)
<asynchronous suspension>
#4      AuthenticationProvider.authenticate (package:cocoon_service/src/request_handling/authentication.dart:95:44)
<asynchronous suspension>
#5      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:87:46)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:63:23)
<asynchronous suspension>
#7      runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#8      runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
#9      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#15     fork (package:gcloud/service_scope.dart:104:30)
#16     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:9)
#17     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#24     _StreamController._add (dart:async/stream_controller.dart:640:7)
#25     _StreamController.add (dart:async/stream_controller.dart:586:5)
#26     _HttpServer._handleRequest (dart:_http/http_impl.dart:2670:19)
#27     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2428:19)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#34     _StreamController._add (dart:async/stream_controller.dart:640:7)
#35     _StreamController.add (dart:async/stream_controller.dart:586:5)
#36     _HttpParser._headersEnd (dart:_http/http_parser.dart:386:17)
#37     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#38     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#39     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#46     _StreamController._add (dart:async/stream_controller.dart:640:7)
#47     _StreamController.add (dart:async/stream_controller.dart:586:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#49     _rootRunUnary (dart:async/zone.dart:1136:13)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by tvolkert** [comment]
Error is originating here: https://github.com/dart-lang/http2/blob/04843721d4778dcba8e9b490efca9c0ea809fec8/lib/src/connection.dart#L461-L463

**Comment by dnfield** [comment]
https://github.com/grpc/grpc-dart/issues/131 seems related

**Comment by tvolkert** [comment]
@mkustermann @sigurdm @a14n any insight?  I'm using appengine 0.10.0, grpc 2.0.3, http2 1.0.0.

**Comment by tvolkert** [comment]
It seems more and more like this may have nothing to do with concurrency issues and just be a  bug in package:http2 (or maybe package:grpc).  I'm going to close this and open a bug in http2.

**Comment by tvolkert** [comment]
Filed as https://github.com/dart-lang/http2/issues/46

**Comment by mkustermann** [comment]
To me the issue seems in the code from [package:grpc/src/client.call.dart](https://github.com/grpc/grpc-dart/blob/master/lib/src/client/call.dart#L165):
```dart
 void _sendRequest(ClientConnection connection, Map<String, String> metadata) {
    try {
      _stream = connection.makeRequest(
          _method.path, options.timeout, metadata, _onRequestError);
    } catch (e) {
      _terminateWithError(GrpcError.unavailable('Error making call: $e'));
      return;
    }
    _requestSubscription = _requests
        .map(_method.requestSerializer)
        .handleError(_onRequestError)
        .listen(_stream.outgoingMessages.add,
            onError: _stream.outgoingMessages.addError,
            onDone: _stream.outgoingMessages.close,
            cancelOnError: true);
    // The response stream might have been listened to before _stream was ready,
    // so try setting up the subscription here as well.
    _onResponseListen();
  }
```
which seems to call [package:grpc/src/client/http2_connection.dart](https://github.com/grpc/grpc-dart/blob/master/lib/src/client/http2_connection.dart#L130):
```dart
  GrpcTransportStream makeRequest(String path, Duration timeout,
      Map<String, String> metadata, ErrorHandler onRequestFailure) {
    final headers = createCallHeaders(
        credentials.isSecure, authority, path, timeout, metadata,
        userAgent: options.userAgent);
    final stream = _transportConnection.makeRequest(headers);
    return Http2TransportStream(stream, onRequestFailure);
  }
```

Any http/2 connection can be in a finishing state (for different reasons, maybe the server wants to close the connection soon, we ran out of stream ids, ...). In this state it's not possible to make new http/2 streams.

Yet this code unconditionally calls `_transportConnection.makeRequest()`, which causes an exception to be thrown, which then eventually results in this error coming from `GrpcDatastoreImpl.lookup()` in the stack from https://github.com/dart-lang/appengine/issues/117#issuecomment-520174092.

What the code should do instead is check whether we're allowed to make new requests (via `_transportConnection.isOpen`), if not, we can simply make a fresh http/2 connection.

In fact until recently `package:appengine` had it's own grpc implementation which handled this better (after 22f7c097a6d0063f  `package:appengine` uses `package:grpc`).

Looking at the former grpc implementation in [package:appengine/src/grpc_api_impl/grpc.dart](https://github.com/dart-lang/appengine/blob/039684887f97bc1281882f1209b0ac66b98349da/lib/src/grpc_api_impl/grpc.dart#L116):
```dart
  Future<T> invoke<T extends protobuf.GeneratedMessage>(String service,
      String method, protobuf.GeneratedMessage request, T response) async {
    ...

    // If the current connection is not healthy we'll make a new one:
    // NOTE: Several concurrent callers will end up using the same dialer and
    // will therefore obtain the same connection.
    // NOTE: It seems like Google's gRPC endpoints will forcefully close the
    // connection after precisely 1 hour. So we *proactively* refresh our
    // connection after 50 minutes. This will avoid one failed RPC call.
    final bool isHealthy = _connection != null && _connection.isOpen;
    final bool shouldRefresh = _stopwatch.elapsed.inMinutes > 50;
    if (!isHealthy || shouldRefresh) {
      if (isHealthy) _connection.finish();
      _connection = await _dialer.dial();
      _stopwatch.reset();
    }
```

=> The comment basically explains it: If the connection `!isHealthy` we will make a new http/2 connection.

Since there can be several such `invoke` calls going on at the same time it uses a [Dialer](https://github.com/dart-lang/appengine/blob/039684887f97bc1281882f1209b0ac66b98349da/lib/src/grpc_api_impl/grpc.dart#L298) to ensure only one new http/2 connection is made:
```dart
/// Used for dialing http/2 endpoints.
///
/// If several callers attempt to dial at the same point in time, only the first
/// one will trigger a http/2 connection attempt and all of them will receive
/// the same connection (or an error).
///
/// The number of http/2 dialing attempts will be rate-limited in order to not
/// flood the server and avoid busy loops where callers constantly attempt
/// to dial a nonexistent/down peer.
class Dialer {
```

**Comment by tvolkert** [comment]
Thanks Martin! Third time's a charm in filing this issue in the correct repo 😄 -- I'm consolidating this comment into grpc/grpc-dart#228
