### ISSUE TITLE
Connecting to datastore emulator doesn't work with v0.7.0+

### ISSUE THREAD

**Issue by enyo** [dart-lang/appengine#123]
We have been running on `v0.6.1` for a while and just upgraded to the latest version but can't connect to our datastore emulator anymore. We checked which version broke it, and appears to be `v0.7.0`: `Refactored to use package:grpc to talk to Logging and Datastore backends.` which fits with the error message we get:

```
  Caught error: Something went wrong while creating the sitemap: gRPC Error (14, Error connecting: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 53263)
  #0      _startServer.<anonymous closure> (package:_server/web_server/server.dart:49:59)
  #1      _rootRunUnary (dart:async/zone.dart:1132:38)
  #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
  #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
  #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
  #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
  #6      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:383:20)
  #7      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:324:15)
  #8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:382:5)
  #9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
  #10     Logger._publish (package:logging/logging.dart:240:19)
  #11     Logger.log (package:logging/logging.dart:190:14)
  #12     Logger.severe (package:logging/logging.dart:221:7)
  #13     createPageSitemap (package:_server/utils/sitemap.dart:39:9)
  <asynchronous suspension>
  #14     _startServer (package:_server/web_server/server.dart:63:9)
  <asynchronous suspension>
  #15     startServer.<anonymous closure> (package:_server/web_server/server.dart:34:60)
  #16     withAppEngineServices.<anonymous closure> (package:appengine/src/appengine_internal.dart:37:51)
  #17     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:110:20)
  <asynchronous suspension>
  #18     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
  #19     _rootRun (dart:async/zone.dart:1124:13)
  #20     _CustomZone.run (dart:async/zone.dart:1021:19)
  #21     _runZoned (dart:async/zone.dart:1516:10)
  #22     runZoned (dart:async/zone.dart:1463:12)
  #23     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
  #24     fork (package:gcloud/service_scope.dart:104:30)
  #25     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:101:10)
  #26     withAppEngineServices (package:appengine/src/appengine_internal.dart:37:5)
  #27     withAppEngineServices (package:appengine/appengine.dart:150:10)
  #28     startServer (package:_server/web_server/server.dart:34:28)
  #29     main (file:///Users/enyo/Develop/exitlive/server/bin/server.dart:6:9)
  <asynchronous suspension>
  #30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
  #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Do you have any suggestion on how to fix this?

**Comment by domesticmouse** [comment]
Sounds like the datastore emulator doesn't do gRPC. I don't currently have time to dig into this, but will happily take pointers if you dig into what is breaking and where. A simplified reproduction sample would be a great start.

**Comment by enyo** [comment]
Thanks. will provide ASAP

**Comment by domesticmouse** [comment]
Sweet, thanks!

**Comment by martflu** [comment]
[Here is a gist](https://gist.github.com/martflu/c1fdc07a22b4b20dd8de8ecbe9e2cb4b) of how to reproduce the problem.

**Comment by enyo** [comment]
Any update on this? Not being able to use the datastore emulator is a big problem for us.

**Comment by enyo** [comment]
@jonasfj @domesticmouse sorry to bump this again, but is there a way this could be looked at? We are unable to upgrade any library at the moment because of this, and it's becoming more and more of a problem.

**Comment by jonasfj** [comment]
> EDIT: Is there a way to connect to the real datastore from my local machine until this is fixed?

@enyo, Yes, see: https://github.com/dart-lang/appengine#running-without-docker
Basically, create a GCP service account and export the key as json. And make sure to give the service account permissions to datastore.

In `pub.dev` development we use a fake in-memory `gcloud` datastore backed for unit tests, and we use a staging site for local development.

--------
On topic, if you're interested in debugging this please dive in. We're happy to take contributions.
Maybe it's just something simple... We could also remove this from the readme, so as to not advertize a feature that doesn't work anymore.

**Comment by enyo** [comment]
Thanks @jonasfj 

I think that in the long run, having a local datastore emulator is quite crucial for development, so it would be great to get this fixed

I'm happy to help debugging this, but I have no idea how the communication between these two services is working. It would be great if somebody who made the breaking change could look at this.
