### ISSUE TITLE
GCLOUD_PROJECT not set

### ISSUE THREAD

**Issue by martflu** [dart-lang/appengine#65]
The deployment of our dart app fails after a time out. When looking at the logs of the instance, it fails to start with following error:
```
Bad state: Expected environment variable GCLOUD_PROJECT to be set!
```
Do we need to set this in our Dockerfile? The README.md suggests that this should only be necessary for local development.

Here is our current `Dockerfile`:
``` Dockerfile
# Dockerfile extending the generic Dart image with application files for a
# single application.

FROM google/dart-runtime-base:1.22

ADD . /project
WORKDIR /project
RUN pub get --packages-dir

# We install memcached and remove the apt-index again to keep the
# docker image diff small.
RUN apt-get update && \
    apt-get install -y memcached && \
    rm -rf /var/lib/apt/lists/*

# Clear out any arguments the base images might have set and ensure we start
# memcached and wait for it to come up before running the Dart app.
CMD []
ENTRYPOINT service memcached start && sleep 1 && /bin/bash /dart_runtime/dart_run.sh
```

and `app.yaml`
``` yaml
runtime: custom
vm: flex
api_version: 1
```

**Comment by mkustermann** [comment]
The environment variable should be provided by the GCE VM which starts the docker container. We have not seen this issue in any of our flex applications so far.

The new environment variable names are described [here](https://cloud.google.com/appengine/docs/flexible/nodejs/upgrading#environment_variable_changes).

The `api_version` must not be supplied in the `app.yaml` afaik. Could you try without this key?

**Comment by martflu** [comment]
Unfortunately, removing `api_version` did not resolve this issue.
Full stacktrace from the console log:
``` dart
Unhandled exception:
 
Bad state: Expected environment variable GCLOUD_PROJECT to be set!
 
#0      _initializeAppEngine.<_initializeAppEngine_async_body>._findEnvironmentVariable (package:appengine/src/appengine_internal.dart:141:7)
#1      _initializeAppEngine.<_initializeAppEngine_async_body> (package:appengine/src/appengine_internal.dart:146:45)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#3      _rootRunUnary (dart:async/zone.dart:1158)
#4      _CustomZone.runUnary (dart:async/zone.dart:1037)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#7      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#8      _Future._complete (dart:async/future_impl.dart:467)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#10     _getZoneInProduction.<_getZoneInProduction_async_body> (package:appengine/src/appengine_internal.dart:368:7)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#12     _rootRunUnary (dart:async/zone.dart:1158)
#13     _CustomZone.runUnary (dart:async/zone.dart:1037)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#16     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#17     _Future._completeWithValue (dart:async/future_impl.dart:477)
#18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#19     _rootRun (dart:async/zone.dart:1150)
#20     _CustomZone.run (dart:async/zone.dart:1026)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:953)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149) 
```

**Comment by enyo** [comment]
We are not supposed to set `GCLOUD_PROJECT` ourselves, are we?

**Comment by martflu** [comment]
Changing `vm: flex` to `env: flex` in the `app.yaml` resolved the problem.
